import { chromium } from 'playwright';
const b = await chromium.launch();
// desktop scroll-pinned state on the dark home
let ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128 Safari/537.36' });
let p = await ctx.newPage(); await p.goto('https://www.synopsys.com/', { waitUntil: 'networkidle', timeout: 90000 }).catch(() => {});
await p.waitForTimeout(1200); const ot = await p.$('#onetrust-accept-btn-handler'); if (ot) { await ot.click().catch(() => {}); await p.waitForTimeout(400); }
await p.evaluate(() => window.scrollTo(0, 400)); await p.waitForTimeout(900);
await p.screenshot({ path: '/tmp/live-home-pinned.png', clip: { x: 0, y: 0, width: 1440, height: 140 } });
console.log('pinned', await p.evaluate(() => { const n = document.querySelector('.component-nav-top'); const cs = getComputedStyle(n); const r = n.getBoundingClientRect(); return { y: r.y, h: r.height, pos: cs.position, bg: cs.backgroundColor, cls: n.className, logoFill: getComputedStyle(document.querySelector('.component-nav-top .logo svg path')).fill, txt: getComputedStyle(document.querySelector('.main-nav-item-header')).color }; }));
await ctx.close();
// mobile: open menu via the real toggle
ctx = await b.newContext({ viewport: { width: 360, height: 800 }, deviceScaleFactor: 2, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1', isMobile: true, hasTouch: true });
p = await ctx.newPage(); await p.goto('https://www.synopsys.com/', { waitUntil: 'networkidle', timeout: 90000 }).catch(() => {});
await p.waitForTimeout(1200); const ot2 = await p.$('#onetrust-accept-btn-handler'); if (ot2) { await ot2.click().catch(() => {}); await p.waitForTimeout(400); }
const cands = await p.evaluate(() => [...document.querySelectorAll('.component-nav-top *')].filter((e) => { const r = e.getBoundingClientRect(); return r.width > 20 && r.width < 80 && r.height > 20 && r.height < 60 && r.x > 250 && r.y < 80; }).map((e) => `${e.tagName}.${e.className}`).slice(0, 8));
console.log('toggle candidates', cands);
const tog = await p.$('.component-nav-top .mobile-menu-toggle, .component-nav-top .hamburger-menu, .component-nav-top .navbar-toggler, .component-nav-top [class*=hamburger], .component-nav-top [class*=toggle], .component-nav-top button');
if (tog) { await tog.tap().catch(async () => tog.click({ force: true }).catch(() => {})); await p.waitForTimeout(1200); await p.screenshot({ path: '/tmp/live-m-open.png', fullPage: false });
  console.log('open', await p.evaluate(() => { const items = [...document.querySelectorAll('.main-nav-item')].filter((e) => e.getBoundingClientRect().width > 0); return { items: items.length, first: items[0] && (() => { const cs = getComputedStyle(items[0]); const r = items[0].getBoundingClientRect(); return { rect: [r.x, r.y, r.width, r.height], bg: cs.backgroundColor, pad: cs.padding, border: cs.borderBottom, font: cs.fontSize + ' ' + cs.fontWeight, color: getComputedStyle(items[0].querySelector('.main-nav-item-header')).color }; })(), navBg: getComputedStyle(document.querySelector('.main-nav')).backgroundColor, wrapper: (() => { const w = document.querySelector('.component-nav-top'); const cs = getComputedStyle(w); return { bg: cs.backgroundColor, h: w.getBoundingClientRect().height }; })(), cta: [...document.querySelectorAll('.component-nav-top a')].filter((a) => /Contact/.test(a.textContent) && a.getBoundingClientRect().width > 0).map((a) => { const cs = getComputedStyle(a); const r = a.getBoundingClientRect(); return [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height), cs.backgroundColor, cs.color]; }) }; }));
  const prod = await p.$('.main-nav-item[data-menu="Products"] .main-nav-item-header'); if (prod) { await prod.tap().catch(async () => prod.click({ force: true }).catch(() => {})); await p.waitForTimeout(1000); await p.screenshot({ path: '/tmp/live-m-products.png' });
    console.log('products-level', await p.evaluate(() => { const back = [...document.querySelectorAll('*')].find((e) => /^Back$/.test(e.textContent.trim()) && e.getBoundingClientRect().width > 0); const hi = [...document.querySelectorAll('.dropdown[data-menu="Products"] .header-item')].filter((e) => e.getBoundingClientRect().width > 0); return { back: back && back.className, headers: hi.length, firstHeader: hi[0] && (() => { const cs = getComputedStyle(hi[0]); const r = hi[0].getBoundingClientRect(); return [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height), cs.fontSize, cs.fontWeight, cs.backgroundColor, cs.borderBottom]; })(), visibleLists: [...document.querySelectorAll('.dropdown[data-menu="Products"] .nav-list')].filter((e) => e.getBoundingClientRect().height > 0).length }; }));
    const hi = await p.$$('.dropdown[data-menu="Products"] .header-item'); for (const hh of hi) { if (await hh.isVisible()) { await hh.tap().catch(() => {}); await p.waitForTimeout(800); await p.screenshot({ path: '/tmp/live-m-products-l3.png' }); break; } } }
}
await ctx.close(); await b.close();
